### ISSUE TITLE
Ux: Prefer to run the search when range handle is released

### ISSUE THREAD

**Issue by SebCorbin** [Terralego/terra-front#46]
On a range filter, the search is run on every 'tick' of a range, leading to a slow UX.

I suggest replacing `onChange` with `onRelease` for better performance.

See https://blueprintjs.com/docs/#core/components/sliders.range-slider

**Comment by mabhub** [comment]
What about `onRelease` **and** a *debounced  (with at least 300/500ms of delay)* `onChange`?

This would avoid generating too much searches and keep UI reactivity.

**Comment by jrmi** [comment]
And only the debounce on the `onChange` ?

**Comment by mabhub** [comment]
I think it would induce a delay between the release of the handle and the last search action.

**Comment by SebCorbin** [comment]
Why so complicated?
